### ISSUE TITLE
pip和conda都无法安装lazyspier

### ISSUE THREAD

**Issue by calzzzx** [Ehco1996/lazySpider#1]
我的配置win7+anaconda+py3.6

**Comment by Ehco1996** [comment]
@Grizzy-bear 能贴上安装时的报错日志么

**Comment by calzzzx** [comment]
我懂了，你指的是本地包安装，我以为是从源上安装

**Comment by calzzzx** [comment]
![aaaaa](https://user-images.githubusercontent.com/29750963/34246876-5febabd2-e66b-11e7-9fc8-6a627f9492aa.PNG)
![bbbb](https://user-images.githubusercontent.com/29750963/34246881-62e9ff0a-e66b-11e7-9c85-1310dc6e0809.PNG)
似乎还是不行，无法导入模块
![cccc](https://user-images.githubusercontent.com/29750963/34246918-849aa50a-e66b-11e7-8772-a5f880deb003.PNG)

**Comment by Ehco1996** [comment]
@Grizzy-bear 

我已经上传到pypi了，按道可以直接用pip安装
![](http://opj9lh0x4.bkt.clouddn.com/17-12-21/49551025.jpg)

这种情况建议升级一下pip看看

**Comment by huaji1992** [comment]
升级了pip也无法安装

**Comment by huaji1992** [comment]
Could not find a version that satisfies the requirement lazyspier (from versions: )
No matching distribution found for lazyspier

**Comment by Kyvrel** [comment]
@Ehco1996 应该是README里的包名写错了，我提了个pr
#2

**Comment by Ehco1996** [comment]
fixed
